[package]
name = "sourmash"
version = "0.1.1"
authors = ["Luiz Irber <luiz.irber@gmail.com>"]

[lib]
name = "sourmash"
crate-type = ["cdylib", "rlib"]

[profile.release]
lto=true

[build-dependencies]
cbindgen = "0.3.3"

[dependencies]
backtrace = "0.3.4"
error-chain = "0.11"
murmurhash3 = "~0.0.5"
ordslice = "0.2.0"
